return {
  'folke/which-key.nvim',
  event = 'VeryLazy',
  opts = {
    preset = 'modern',
    delay = 300,
    -- hide mappings without a description — unnamed plugin noise
    filter = function(mapping)
      return mapping.desc and mapping.desc ~= ''
    end,
    -- do not pop up in non-editor buffers (terminal/quickfix/help/…)
    disable = { bt = { 'terminal', 'quickfix', 'help', 'nofile', 'prompt' } },
    icons = {
      mappings = false,
      keys = vim.g.have_nerd_font and {} or {
        Up = '<Up> ',
        Down = '<Down> ',
        Left = '<Left> ',
        Right = '<Right> ',
        C = '<C-…> ',
        M = '<M-…> ',
        D = '<D-…> ',
        S = '<S-…> ',
        CR = '<CR> ',
        Esc = '<Esc> ',
        ScrollWheelDown = '<ScrollWheelDown> ',
        ScrollWheelUp = '<ScrollWheelUp> ',
        NL = '<NL> ',
        BS = '<BS> ',
        Space = '<Space> ',
        Tab = '<Tab> ',
        F1 = '<F1>',
        F2 = '<F2>',
        F3 = '<F3>',
        F4 = '<F4>',
        F5 = '<F5>',
        F6 = '<F6>',
        F7 = '<F7>',
        F8 = '<F8>',
        F9 = '<F9>',
        F10 = '<F10>',
        F11 = '<F11>',
        F12 = '<F12>',
      },
    },
    spec = {
      { '<leader>c', group = 'code', mode = { 'n', 'x' } },
      { '<leader>d', group = 'debug' },
      { '<leader>r', group = 'rename' },
      { '<leader>s', group = 'search' },
      { '<leader>w', proxy = '<c-w>', group = 'windows' },
      { '<leader>t', group = 'tools' },
      { '<leader>g', group = 'git', mode = { 'n', 'v' } },
      { '<leader>gd', group = 'diff', mode = { 'n', 'v' } },
      { 'gz', group = 'surround', mode = { 'n', 'x' } },
    },
  },
}
