# =================================================================================================
# Global hotkeys (cannot conflict with other hotkeys)
confirm = ['enter', 'right', 'e']
quit = ['q', 'esc']
# movement
list_up = ['up', 'a']
list_down = ['down', 'h']
page_up = ['pgup','']
page_down = ['pgdown','']
# file panel control
create_new_file_panel = ['n', '']
close_file_panel = ['w', '']
next_file_panel = ['tab', 'E']
previous_file_panel = ['shift+left', 'Y']
toggle_file_preview_panel = ['f', '']
open_sort_options_menu = ['o', '']
toggle_reverse_sort = ['R', '']
# change focus
focus_on_process_bar = ['p', '']
focus_on_sidebar = ['s', '']
focus_on_metadata = ['m', '']
# create file/directory and rename
file_panel_item_create = ['ctrl+n', '']
file_panel_item_rename = ['ctrl+r', '']
# file operations
copy_items = ['ctrl+c', '']
cut_items = ['ctrl+x', '']
paste_items = ['ctrl+v', '']
delete_items = ['ctrl+d', 'delete', '']
# compress and extract
extract_file = ['ctrl+e', '']
compress_file = ['ctrl+a', '']
# editor
open_file_with_editor = ['k', '']
open_current_directory_with_editor = ['K', '']
# other
pinned_directory = ['P', '']
toggle_dot_file = ['.', '']
change_panel_mode = ['v', '']
open_help_menu = ['?', '']
open_command_line = [':', '']
copy_path = ['ctrl+p', '']
copy_present_working_directory = ['c', '']
toggle_footer = ['F', '']
# =================================================================================================
# Typing hotkeys (can conflict with all hotkeys)
confirm_typing = ['enter', '']
cancel_typing = ['ctrl+c', 'esc']
# =================================================================================================
# Normal mode hotkeys (can conflict with other modes, cannot conflict with global hotkeys)
parent_directory = ['y', 'left', 'backspace']
search_bar = ['/', '']
# =================================================================================================
# Select mode hotkeys (can conflict with other modes, cannot conflict with global hotkeys)
file_panel_select_mode_items_select_down = ['shift+down', 'H']
file_panel_select_mode_items_select_up = ['shift+up', 'A']
file_panel_select_all_items = ['j', '']
